spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            auth: true
          ssl:
            enable: true

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  servlet:
     multipart:
       max-request-size: 100MB
       max-file-size: 100MB

  cache:
    type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

jwt:
  access-secret: ${JWT_ACCESS}
  refresh-secret: ${JWT_REFRESH}

server:
  port: ${SERVER_PORT}


cloud:
  aws:
    region:
      static : ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: false
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
      url: ${S3_URL}
