spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: ${MAIL_ENABLE}
            auth: ${MAIL_AUTH}
          ssl:
            enable: ${MAIL_SSL_ENABLE}
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  main:
    allow-bean-definition-overriding: ${MAIN_OVERRIDING}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL}
    defer-datasource-initialization: ${JPA_INITIAL}

  servlet:
     multipart:
       max-request-size: ${MAX_REQ_SIZE}
       max-file-size: ${MAX_FILE_SIZE}

  cache:
    type: ${REDIS}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

jwt:
  access-secret: ${JWT_ACCESS}
  refresh-secret: ${JWT_REFRESH}

server:
  port: ${SERVER_PORT}

cloud:
  aws:
    region:
      static : ${AWS_REGION}
    stack:
      auto: ${AWS_STACK}
    credentials:
      instance-profile: ${AWS_PROFILE}
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
      url: ${S3_URL}
